version: "3.1"

volumes:
  claritydb:

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: clarity
      MYSQL_USER: clarityuser
      MYSQL_PASSWORD: claritypassword
    volumes:
      - claritydb:/var/lib/mysql

  clarity:
    image: clarity
    build: .
    environment:
      SECRET_KEY: temporarytestkey
      SQLALCHEMY_DATABASE_URI: mysql://clarityuser:claritypassword@db/clarity
      #SQLALCHEMY_DATABASE_URI: sqlite:///db.sqlite
      ALLOW_SIGNUP: "False"
    ports:
      - 80:80

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
